/*
 * generated by Xtext 2.12.0
 */
package org.archware.sosadl.tests

import com.google.inject.Inject
import org.archware.sosadl.sosADL.SosADL
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(SosADLInjectorProvider)
class SosADLParsingTest {
	@Inject
	ParseHelper<SosADL> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
