/*
 * generated by Xtext
 */
package org.archware.sosadl.validation

import org.archware.sosadl.sosADL.SosADL
import org.eclipse.xtext.validation.Check
import org.archware.sosadl.validation.typing.TypeChecker

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class SosADLValidator extends AbstractSosADLValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def typecheck(SosADL file) {
		try {
			var tc = new TypeChecker();
			tc.typecheck(file);
			tc.consumeErrors[notifyError];
		} catch(Throwable t) {
			t.printStackTrace();
			error("Bug in the type checker", file, null);
			throw t;
		}
	}
	
	private def notifyError(ValidationError e) {
		error(e.message, e.target, e.feature, e.index);
	}
}
