/*
 * generated by Xtext 2.12.0
 */
package org.archware.sosadl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SosADLRuntimeModule extends AbstractSosADLRuntimeModule {
}
