/**
 * generated by Xtext 2.12.0
 */
package org.archware.sosadl.ide;

import org.archware.sosadl.ide.AbstractSosADLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SosADLIdeModule extends AbstractSosADLIdeModule {
}
